WOOC-442

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -28,4 +28,9 @@ jobs:
         run: vendor/bin/phpcs --config-set installed_paths vendor/phpcompatibility/php-compatibility
       - name: Test php version 5.3
         run: ./vendor/bin/phpcs -p -v --colors ./src/ --standard=PHPCompatibility --runtime-set testVersion 5.3
+      - uses: actions/upload-artifact@v2  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: test-results
+          path: jest-junit.xml
       - run: echo "🍏 This job's status is ${{ job.status }}."
